import { Router } from 'express'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import crypto from 'node:crypto'; import { z } from 'zod'; import { User,Lead,Customer,Company,Contact,Deal,Task,Activity,Meeting,Note,Notification } from '../models/index.js'; import { requireAuth,allow } from '../middleware/auth.js'; import { wrap,ok } from '../utils/async.js'; import { sendEmail } from '../services/email.js';
const router=Router(); const cookieOpts={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const};
const access=(id:string)=>jwt.sign({id},process.env.JWT_ACCESS_SECRET||'dev-access-secret-change-me',{expiresIn:'15m'}); const refresh=(id:string)=>jwt.sign({id},process.env.JWT_REFRESH_SECRET||'dev-refresh-secret-change-me',{expiresIn:'7d'});
const session=async(res:import('express').Response,user: {id:string;name:string;email:string;role:string})=>{const r=refresh(user.id);await User.findByIdAndUpdate(user.id,{refreshTokenHash:await bcrypt.hash(r,10)});res.cookie('accessToken',access(user.id),{...cookieOpts,maxAge:15*60*1000}).cookie('refreshToken',r,{...cookieOpts,path:'/api/auth',maxAge:7*24*60*60*1000});return ok(res,{user});};
router.post('/auth/register',wrap(async(req,res)=>{const d=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10)}).parse(req.body);const user=await User.create({...d,email:d.email.toLowerCase(),password:await bcrypt.hash(d.password,12)});return session(res,{id:user.id,name:user.name,email:user.email,role:user.role})}));
router.post('/auth/login',wrap(async(req,res)=>{const d=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const u=await User.findOne({email:d.email.toLowerCase()}).select('+password');if(!u||u.status!=='Active'||!await bcrypt.compare(d.password,u.password))return res.status(401).json({success:false,message:'Email or password is incorrect',errors:[]});return session(res,{id:u.id,name:u.name,email:u.email,role:u.role})}));
router.post('/auth/refresh',wrap(async(req,res)=>{const token=req.cookies?.refreshToken as string|undefined;if(!token)return res.status(401).json({success:false,message:'Session expired',errors:[]});try{const {id}=jwt.verify(token,process.env.JWT_REFRESH_SECRET||'dev-refresh-secret-change-me') as {id:string};const u=await User.findById(id).select('+refreshTokenHash');if(!u?.refreshTokenHash||!await bcrypt.compare(token,u.refreshTokenHash))throw new Error('Invalid session');return session(res,{id:u.id,name:u.name,email:u.email,role:u.role})}catch{return res.status(401).json({success:false,message:'Session expired',errors:[]})}}));
router.post('/auth/logout',wrap(async(req,res)=>{const token=req.cookies?.refreshToken as string|undefined;if(token)try{const {id}=jwt.verify(token,process.env.JWT_REFRESH_SECRET||'dev-refresh-secret-change-me') as {id:string};await User.findByIdAndUpdate(id,{refreshTokenHash:null})}catch{}res.clearCookie('accessToken',cookieOpts).clearCookie('refreshToken',{...cookieOpts,path:'/api/auth'});return ok(res,{message:'Signed out'})}));
router.get('/auth/me',requireAuth,wrap(async(req,res)=>ok(res,{user:await User.findById(req.user!.id).select('-refreshTokenHash')})));
router.post('/auth/forgot-password',wrap(async(req,res)=>{const {email}=z.object({email:z.string().email()}).parse(req.body);const u=await User.findOne({email:email.toLowerCase()});if(u){const token=crypto.randomBytes(32).toString('hex');u.resetTokenHash=crypto.createHash('sha256').update(token).digest('hex');u.resetTokenExpires=new Date(Date.now()+3600000);await u.save();const link=`${process.env.CLIENT_URL}/reset-password/${token}`;await sendEmail(u.email,'Reset your ClientFlow password',`<p>Reset your password within one hour: <a href="${link}">Reset password</a></p>`)}return ok(res,{message:'If the account exists, a reset link has been sent'})}));
router.post('/auth/reset-password/:token',wrap(async(req,res)=>{const password=z.string().min(10).parse(req.body.password);const hash=crypto.createHash('sha256').update(String(req.params.token)).digest('hex');const u=await User.findOne({resetTokenHash:hash,resetTokenExpires:{$gt:new Date()}});if(!u)return res.status(400).json({success:false,message:'Reset link is invalid or expired',errors:[]});u.password=await bcrypt.hash(password,12);u.resetTokenHash=undefined;u.resetTokenExpires=undefined;await u.save();return ok(res,{message:'Password updated'})}));
router.post('/auth/change-password',requireAuth,wrap(async(req,res)=>{const d=z.object({currentPassword:z.string(),password:z.string().min(10)}).parse(req.body);const u=await User.findById(req.user!.id).select('+password');if(!u||!await bcrypt.compare(d.currentPassword,u.password))return res.status(400).json({success:false,message:'Current password is incorrect',errors:[]});u.password=await bcrypt.hash(d.password,12);await u.save();return ok(res,{message:'Password updated'})}));
router.use(requireAuth);
const resources={users:User,leads:Lead,customers:Customer,companies:Company,contacts:Contact,deals:Deal,tasks:Task,activities:Activity,meetings:Meeting,notes:Note,notifications:Notification} as const;
const populatePaths:Record<string,string[]>={leads:['assignedTo','convertedCustomer'],customers:['assignedTo','sourceLead'],companies:['assignedTo'],contacts:['company','owner'],deals:['company','customer','contact','owner'],tasks:['assignedTo','relatedLead','relatedCustomer','relatedDeal'],activities:['actor','relatedLead','relatedCustomer','relatedContact','relatedDeal','relatedCompany'],meetings:['attendees','organizer','relatedCustomer','relatedLead','relatedDeal'],notes:['author','relatedLead','relatedCustomer','relatedContact','relatedDeal','relatedCompany'],notifications:['user']};
for(const [path,Model] of Object.entries(resources)){const adminOnly=path==='users';router.get(`/${path}`,wrap(async(req,res)=>{const {q,page='1',limit='50',...filters}=req.query;const query:Record<string,unknown>={};for(const [k,v] of Object.entries(filters))if(v&&k!=='undefined')query[k]=v; if(path==='users'&&req.user!.role!=='Admin')query._id=req.user!.id;if(q){const searchable=path==='leads'?['firstName','lastName','email','company']:path==='contacts'?['firstName','lastName','email']:path==='deals'?['title']:['name','title','email','company'];query.$or=searchable.map(k=>({[k]:{$regex:String(q),$options:'i'}}))}const p=Math.max(1,Number(page)),n=Math.min(100,Math.max(1,Number(limit)));const find=Model.find(query).sort({createdAt:-1}).skip((p-1)*n).limit(n);for(const field of populatePaths[path]||[])find.populate(field,'name firstName lastName title email role');const [items,total]=await Promise.all([find.lean(),Model.countDocuments(query)]);return ok(res,{items,total,page:p,pages:Math.ceil(total/n)})}));router.post(`/${path}`,...(adminOnly?[allow('Admin')]:[]),wrap(async(req,res)=>{if(path==='users'){const d=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10),role:z.string(),phone:z.string().optional(),department:z.string().optional(),jobTitle:z.string().optional()}).parse(req.body);req.body={...d,password:await bcrypt.hash(d.password,12)}}const item=await Model.create(req.body);return ok(res,{item},201)}));router.get(`/${path}/:id`,wrap(async(req,res)=>{const find=Model.findById(req.params.id);for(const field of populatePaths[path]||[])find.populate(field,'name firstName lastName title email role');const item=await find;if(!item)return res.status(404).json({success:false,message:'Record not found',errors:[]});return ok(res,{item})}));router.patch(`/${path}/:id`,...(adminOnly?[allow('Admin')]:[]),wrap(async(req,res)=>{if(path==='users'&&req.body.password)req.body.password=await bcrypt.hash(req.body.password,12);const item=await Model.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!item)return res.status(404).json({success:false,message:'Record not found',errors:[]});return ok(res,{item})}));router.delete(`/${path}/:id`,...(adminOnly?[allow('Admin')]:[]),wrap(async(req,res)=>{const item=path==='users'?await User.findByIdAndUpdate(req.params.id,{status:'Inactive'},{new:true}):await Model.findByIdAndDelete(req.params.id);if(!item)return res.status(404).json({success:false,message:'Record not found',errors:[]});return ok(res,{message:'Record removed'} )}))}
router.get('/dashboard',wrap(async(_req,res)=>{
 const [leads,customers,deals,tasks,meetings,leadSources,leadStatuses,stages,monthly]=await Promise.all([
  Lead.countDocuments(),Customer.countDocuments(),Deal.find().lean(),
  Task.countDocuments({status:{$in:['Pending','In Progress']}}),
  Meeting.countDocuments({status:'Scheduled',date:{$gte:new Date()}}),
  Lead.aggregate([{$group:{_id:'$source',count:{$sum:1}}}]),
  Lead.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]),
  Deal.aggregate([{$group:{_id:'$stage',count:{$sum:1},value:{$sum:'$value'}}}]),
  Deal.aggregate([{$match:{stage:'Won'}},{$group:{_id:{$dateToString:{format:'%Y-%m',date:'$updatedAt'}},revenue:{$sum:'$value'},count:{$sum:1}}},{$sort:{_id:1}},{$limit:12}])
 ]);
 return ok(res,{metrics:{leads,customers,activeDeals:deals.filter(d=>!['Won','Lost'].includes(d.stage)).length,wonDeals:deals.filter(d=>d.stage==='Won').length,lostDeals:deals.filter(d=>d.stage==='Lost').length,pipelineValue:deals.filter(d=>!['Won','Lost'].includes(d.stage)).reduce((s,d)=>s+d.value,0),wonRevenue:deals.filter(d=>d.stage==='Won').reduce((s,d)=>s+d.value,0),pendingTasks:tasks,upcomingMeetings:meetings},leadSources,leadStatuses,stages,monthly});
}));
router.get('/reports',wrap(async(_req,res)=>{const [deals,leads,team]=await Promise.all([Deal.aggregate([{$group:{_id:'$stage',count:{$sum:1},value:{$sum:'$value'}}}]),Lead.aggregate([{$group:{_id:'$source',count:{$sum:1}}}]),Deal.aggregate([{$group:{_id:'$owner',count:{$sum:1},value:{$sum:'$value'},won:{$sum:{$cond:[{$eq:['$stage','Won']},1,0]}}}},{$lookup:{from:'users',localField:'_id',foreignField:'_id',as:'user'}},{$project:{name:{$arrayElemAt:['$user.name',0]},count:1,value:1,won:1}}])]);return ok(res,{deals,leads,team})}));
router.get('/search',wrap(async(req,res)=>{const q=String(req.query.q||'').trim();if(q.length<2)return ok(res,{results:[]});const rx={$regex:q,$options:'i'};const [leads,customers,contacts,companies,deals]=await Promise.all([Lead.find({$or:[{firstName:rx},{lastName:rx},{email:rx},{company:rx}]}).limit(5).lean(),Customer.find({$or:[{name:rx},{email:rx},{company:rx}]}).limit(5).lean(),Contact.find({$or:[{firstName:rx},{lastName:rx},{email:rx}]}).limit(5).lean(),Company.find({name:rx}).limit(5).lean(),Deal.find({title:rx}).limit(5).lean()]);return ok(res,{results:[...leads.map(x=>({type:'Lead',id:x._id,label:`${x.firstName} ${x.lastName}`,detail:x.company})),...customers.map(x=>({type:'Customer',id:x._id,label:x.name,detail:x.company})),...contacts.map(x=>({type:'Contact',id:x._id,label:`${x.firstName} ${x.lastName}`,detail:x.email})),...companies.map(x=>({type:'Company',id:x._id,label:x.name,detail:x.industry})),...deals.map(x=>({type:'Deal',id:x._id,label:x.title,detail:x.stage}))]})}));
export default router;
